#!/usr/bin/env bash
# Installs and configures Nginx to serve a page containing "Holberton School" at root /

sudo apt-get update -y
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

sudo nginx -t
sudo nginx -s reload 2>/dev/null || sudo nginx


